import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { bgMain } from "@/constants/Colors";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen custom-scrollbar">
      <body className={`${inter.className} min-h-screen`} style={{backgroundColor : bgMain}}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
